SystemUI: Create expandable volume panel.
Change-Id: I67fffddc6f97d25b6e5076b2a6e983b9299b20a9

Conflicts:
	packages/SystemUI/res/layout/volume_panel.xml

SystemUI: reset timeout when expanding volume panel

Change-Id: Iad3ba9367d12c60807347baf3e7c06a9d0b7d49a

VolumePanel : Check if StreamControl is null

Avoids npe

Change-Id: Ib89ea79ce6a95ffc80b0fcc163f57b6a367ea8d4

ExpandedVolumePanel: Fix SystemUI FC when expands volume panel from Notifications tile

java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

Change-Id: I3f5acf5e39e01cd74b7d039bc2189a9009f2abe7